# Generated by Django 5.0.8 on 2025-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintattachment",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Size in bytes",
                null=True,
                verbose_name="File Size",
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="File Type"
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Original Name"
            ),
        ),
    ]
