# Generated by Django 5.0.8 on 2025-08-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintcomment",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
    ]
