# Generated by Django 5.0.8 on 2025-08-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_alter_complaintcomment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintattachment",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Size in bytes",
                null=True,
                verbose_name="File Size",
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="File Type"
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the file as uploaded by user",
                max_length=255,
                null=True,
                verbose_name="Original Name",
            ),
        ),
    ]
